export enum OrderPaymentStatusEnum {
    PENDING = 'PENDING',
    AUTHORIZED = 'AUTHORIZED',
    AWAITING_SETTLEMENT = 'AWAITING_SETTLEMENT',
    PARTIALLY_PAID = 'PARTIALLY_PAID',
    PAID = 'PAID',
    VOIDED = 'VOIDED',
    PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
    REFUNDED = 'REFUNDED',
}